services:
    pgsql:
        image: postgres:16.8-alpine
        restart: always
        ports:
            - 5432:5432
        volumes:
            - postgres:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: ${PGPASSWORD}
    composer:
        image: composer:2.8.7
        restart: on-failure
        working_dir: /app
        volumes:
            - ./:/app
        command: composer install
    php:
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
        working_dir: /app
        volumes:
            - ./:/app:ro
            - ./Caddyfile:/etc/caddy/Caddyfile:ro
        depends_on:
            - pgsql
            - composer
    varnish:
        image: varnish:7.7.0-alpine
        restart: always
        ports:
            - 63342:80
        volumes:
            - ./default.vcl:/etc/varnish/default.vcl:ro
        depends_on:
            - php
volumes:
    postgres:
        name: postgres
