services:
    postgres:
        container_name: postgres
        image: postgres:16.8-alpine
        restart: always
        ports:
            - 5432:5432
        volumes:
            - postgres:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: ${PGDATABASE}
            POSTGRES_USER: ${PGUSER}
            POSTGRES_PASSWORD: ${PGPASSWORD}
    pnpm:
        container_name: pnpm
        image: gplane/pnpm:10.6.5-alpine
        restart: always
        working_dir: /app
        volumes:
            - ./package.json:/app/package.json:ro
            - ./pnpm-lock.yaml:/app/pnpm-lock.yaml:ro
            - ./.env.example:/app/.env.example:ro
            - ./esbuild.config.js:/app/esbuild.config.js:ro
            - ./src:/app/src:ro
            - ./assets:/app/assets
            - ./public:/app/public
        command: sh -c "pnpm i && pnpm dev"
    composer:
        container_name: composer
        image: composer:2.8.7
        restart: on-failure
        working_dir: /app
        volumes:
            - ./composer.json:/app/composer.json:ro
            - ./composer.lock:/app/composer.lock:ro
            - ./vendor:/app/vendor
        command: sh -c "composer i"
    php:
        container_name: php
        restart: always
        build:
            context: .
            dockerfile: php/Dockerfile
        working_dir: /app
        volumes:
            - ./public:/app/public:ro
            - ./src:/app/src:ro
            - ./svg:/app/svg:ro
            - ./vendor:/app/vendor:ro
            - ./.env:/app/.env:ro
            - ./php.ini:/app/php.ini:ro
            - ./Caddyfile:/etc/caddy/Caddyfile:ro
        depends_on:
            - postgres
            - pnpm
            - composer
    nginx:
        container_name: nginx
        restart: always
        build:
            context: .
            dockerfile: nginx/Dockerfile
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
            - ./htpasswd.sh:/htpasswd.sh:ro
        depends_on:
            - php
    varnish:
        container_name: varnish
        image: varnish:7.7.0-alpine
        restart: always
        ports:
            - 63342:80
        volumes:
            - ./default.vcl:/etc/varnish/default.vcl:ro
        depends_on:
            - php
volumes:
    postgres:
        name: postgres
