services:
    postgres:
        container_name: postgres
        image: postgres:16.8-alpine
        restart: always
        ports:
            - 5432:5432
        volumes:
            - postgres:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: ${PGPASSWORD}
    composer:
        container_name: composer
        image: composer:2.8.7
        restart: on-failure
        working_dir: /app
        volumes:
            - ./composer.json:/app/composer.json:ro
            - ./composer.lock:/app/composer.lock:ro
            - ./vendor:/app/vendor
        command: composer install
    php:
        container_name: php
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
        working_dir: /app
        volumes:
            - ./public:/app/public:ro
            - ./src:/app/src:ro
            - ./svg:/app/svg:ro
            - ./vendor:/app/vendor:ro
            - ./.env:/app/.env:ro
            - ./php.ini:/app/php.ini:ro
            - ./Caddyfile:/etc/caddy/Caddyfile:ro
        depends_on:
            - postgres
            - composer
    varnish:
        container_name: varnish
        image: varnish:7.7.0-alpine
        restart: always
        ports:
            - 63342:80
        volumes:
            - ./default.vcl:/etc/varnish/default.vcl:ro
        depends_on:
            - php
volumes:
    postgres:
        name: postgres
